timeout: 10s # 连接超时
read_timeout: 2s # 读超时
write_timeout: 2s # 写超时

default:
    host: 192.168.0.103 # ip地址
    port: 6379 # 端口
    db: 0 #db
    timeout: 10s # 连接超时
    read_timeout: 2s # 读超时
    write_timeout: 2s # 写超时
